name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Setup .NET Framework 3.5
      run: Enable-WindowsOptionalFeature -Online -FeatureName "Netfx3" -All

    - name: Build
      run: dotnet msbuild -property:Configuration=Release
